export interface ChurchTheme {
  primary: string;
  accent: string;
  dark: string;
  surface: string;
}
export interface ChurchFeatures {
  sermons: boolean;
  events: boolean;
  ministries: boolean;
  giving: boolean;
  ai: boolean;
  live: boolean;
  community: boolean;
}
export interface ChurchConfig {
  name: string;
  tagline: string;
  description: string;
  url: string;
  logo: string;
  ogImage: string;
  locale: string;
  currency: string;
  timezoneOffsetMin: number;
  motifs: boolean;
  theme: ChurchTheme;
  features: ChurchFeatures;
}

/**
 * THE ONE FILE TO CUSTOMISE PER CHURCH.
 * Generated by scripts/new-church.mjs — edit scripts/new-church.config.json and re-run to change.
 */
export const CHURCH: ChurchConfig = {
  name: "Kharis Builders",
  tagline: "Built on grace, growing in faith.",
  description: "Kharis Builders is a Christ-centred church family building lives on the foundation of God's grace — through worship, sound teaching, and authentic community.",
  url: "https://kharisbuilders.missdiasporagh.workers.dev",
  logo: '/images/logo.png',
  ogImage: '/images/placeholder-wide.svg',
  locale: "en",
  currency: "GHS",
  timezoneOffsetMin: 0,
  motifs: false,
  theme: { primary: "#3b3a6b", accent: "#b08a3e", dark: "#23223f", surface: "#f7f7fb" },
  features: { sermons: true, events: true, ministries: true, giving: true, ai: true, live: true, community: true },
};

export function feature(name: keyof ChurchFeatures): boolean {
  return CHURCH.features[name];
}
