// Pure template-provisioning core: validation + file renderers.
// No fs, no network, no third-party imports — runnable by plain `node` and by vitest.

/**
 * @typedef {{ primary: string, accent: string, dark: string, surface: string }} ChurchTheme
 * @typedef {{ sermons: boolean, events: boolean, ministries: boolean, giving: boolean, ai: boolean, live: boolean }} ChurchFeatures
 * @typedef {{ worker: string, database: string, bucket: string, vectorize: string }} DerivedNames
 * @typedef {{ name: string, slug: string, tagline: string, description: string, url: string, locale: string, currency: string, timezoneOffsetMin: number, motifs: boolean, theme: ChurchTheme, features: ChurchFeatures, names: DerivedNames }} ChurchInput
 */

const SLUG_RE = /^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])$/;
const HEX_RE = /^#[0-9a-fA-F]{6}$/;
const FEATURE_KEYS = ['sermons', 'events', 'ministries', 'giving', 'ai', 'live', 'community'];

/** @param {string} slug @returns {DerivedNames} */
export function deriveNames(slug) {
  return { worker: slug, database: slug, bucket: `${slug}-media`, vectorize: `${slug}-sermons` };
}

/**
 * @param {unknown} raw
 * @returns {{ ok: true, value: ChurchInput } | { ok: false, errors: string[] }}
 */
export function validateChurchInput(raw) {
  const errors = [];
  const r = /** @type {any} */ (raw ?? {});
  const nonEmpty = (k) => typeof r[k] === 'string' && r[k].trim().length > 0;

  for (const k of ['name', 'tagline', 'description', 'url', 'locale']) {
    if (!nonEmpty(k)) errors.push(`"${k}" must be a non-empty string`);
  }
  if (typeof r.slug !== 'string' || !SLUG_RE.test(r.slug)) {
    errors.push('"slug" must be lowercase letters/digits/hyphens, 2–40 chars, no leading/trailing hyphen');
  }
  if (r.slug === 'example-church') {
    errors.push('"slug" is still the example value — copy scripts/new-church.config.example.json to scripts/new-church.config.json and edit it first');
  }
  if (typeof r.currency !== 'string' || !/^[A-Z]{3}$/.test(r.currency)) {
    errors.push('"currency" must be a 3-letter uppercase code (e.g. USD, GHS)');
  }
  if (!Number.isInteger(r.timezoneOffsetMin) || r.timezoneOffsetMin < -720 || r.timezoneOffsetMin > 840) {
    errors.push('"timezoneOffsetMin" must be an integer between -720 and 840');
  }
  if (typeof r.motifs !== 'boolean') errors.push('"motifs" must be a boolean');

  let customDomain;
  if (r.customDomain !== undefined && r.customDomain !== '') {
    if (typeof r.customDomain !== 'string' || !/^([a-z0-9-]+\.)+[a-z]{2,}$/i.test(r.customDomain)) {
      errors.push('"customDomain" must be a hostname like church.example.org (or omit it / leave it empty for a *.workers.dev URL)');
    } else {
      customDomain = r.customDomain;
    }
  }

  const t = r.theme ?? {};
  for (const k of ['primary', 'accent', 'dark', 'surface']) {
    if (typeof t[k] !== 'string' || !HEX_RE.test(t[k])) errors.push(`"theme.${k}" must be a 6-digit hex colour like #3b3a6b`);
  }
  const f = r.features ?? {};
  for (const k of FEATURE_KEYS) {
    if (typeof f[k] !== 'boolean') errors.push(`"features.${k}" must be a boolean`);
  }

  if (errors.length) return { ok: false, errors };

  const value = {
    name: r.name, slug: r.slug, tagline: r.tagline, description: r.description, url: r.url,
    locale: r.locale, currency: r.currency, timezoneOffsetMin: r.timezoneOffsetMin, motifs: r.motifs,
    theme: { primary: t.primary, accent: t.accent, dark: t.dark, surface: t.surface },
    features: Object.fromEntries(FEATURE_KEYS.map((k) => [k, f[k]])),
    names: deriveNames(r.slug),
    customDomain,
  };
  return { ok: true, value };
}

/** @param {ChurchInput} input @returns {string} */
export function renderChurchConfigTs(input) {
  const s = (v) => JSON.stringify(v); // safe double-quoted JS/TS string
  const { theme: th, features: ft } = input;
  return `export interface ChurchTheme {
  primary: string;
  accent: string;
  dark: string;
  surface: string;
}
export interface ChurchFeatures {
  sermons: boolean;
  events: boolean;
  ministries: boolean;
  giving: boolean;
  ai: boolean;
  live: boolean;
  community: boolean;
}
export interface ChurchConfig {
  name: string;
  tagline: string;
  description: string;
  url: string;
  logo: string;
  ogImage: string;
  locale: string;
  currency: string;
  timezoneOffsetMin: number;
  motifs: boolean;
  theme: ChurchTheme;
  features: ChurchFeatures;
}

/**
 * THE ONE FILE TO CUSTOMISE PER CHURCH.
 * Generated by scripts/new-church.mjs — edit scripts/new-church.config.json and re-run to change.
 */
export const CHURCH: ChurchConfig = {
  name: ${s(input.name)},
  tagline: ${s(input.tagline)},
  description: ${s(input.description)},
  url: ${s(input.url)},
  logo: '/images/logo-placeholder.svg',
  ogImage: '/images/placeholder-wide.svg',
  locale: ${s(input.locale)},
  currency: ${s(input.currency)},
  timezoneOffsetMin: ${input.timezoneOffsetMin},
  motifs: ${input.motifs},
  theme: { primary: ${s(th.primary)}, accent: ${s(th.accent)}, dark: ${s(th.dark)}, surface: ${s(th.surface)} },
  features: { sermons: ${ft.sermons}, events: ${ft.events}, ministries: ${ft.ministries}, giving: ${ft.giving}, ai: ${ft.ai}, live: ${ft.live}, community: ${ft.community} },
};

export function feature(name: keyof ChurchFeatures): boolean {
  return CHURCH.features[name];
}
`;
}

/** @param {DerivedNames} names @param {string=} customDomain @returns {string} */
export function renderWranglerJsonc(names, customDomain) {
  const routesBlock = customDomain
    ? `\t"routes": [\n\t\t{ "pattern": "${customDomain}", "custom_domain": true }\n\t],\n`
    : '';
  return `{
\t"compatibility_date": "2026-06-02",
\t"compatibility_flags": ["nodejs_compat", "global_fetch_strictly_public"],
\t"name": "${names.worker}",
${routesBlock}\t"main": "@astrojs/cloudflare/entrypoints/server",
\t"assets": {
\t\t"directory": "./dist",
\t\t"binding": "ASSETS"
\t},
\t"observability": {
\t\t"enabled": true
\t},
\t// Structured content (sermons, events, ministries, visitors, donations, settings).
\t// database_id is filled in after \`wrangler d1 create ${names.database}\`.
\t"d1_databases": [
\t\t{
\t\t\t"binding": "DB",
\t\t\t"database_name": "${names.database}",
\t\t\t"database_id": "PASTE_FROM_D1_CREATE"
\t\t}
\t],
\t// Uploaded media (event/ministry images, sermon thumbnails, portraits).
\t"r2_buckets": [
\t\t{
\t\t\t"binding": "MEDIA",
\t\t\t"bucket_name": "${names.bucket}"
\t\t}
\t],
\t// Session storage required by the Astro Cloudflare adapter.
\t// id is filled in after \`wrangler kv namespace create SESSION\`.
\t"kv_namespaces": [
\t\t{
\t\t\t"binding": "SESSION",
\t\t\t"id": "PASTE_FROM_KV_CREATE"
\t\t}
\t],
\t// Workers AI (embeddings + study-guide generation) and Vectorize (sermon search index).
\t"ai": { "binding": "AI" },
\t"vectorize": [
\t\t{ "binding": "SERMONS", "index_name": "${names.vectorize}" }
\t]
}
`;
}

/** @type {Record<'wide'|'portrait'|'card'|'logo', (t: ChurchTheme) => string>} */
export const retintSvg = {
  wide: ({ primary, accent, dark }) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 900" role="img" aria-label="Placeholder image">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${primary}"/>
      <stop offset="1" stop-color="${dark}"/>
    </linearGradient>
  </defs>
  <rect width="1600" height="900" fill="url(#g)"/>
  <g fill="none" stroke="${accent}" stroke-opacity="0.45" stroke-width="6">
    <circle cx="800" cy="430" r="120"/>
    <circle cx="800" cy="430" r="70"/>
  </g>
  <circle cx="800" cy="430" r="14" fill="${accent}" fill-opacity="0.55"/>
  <text x="1560" y="868" font-family="system-ui, sans-serif" font-size="26" fill="#ffffff" fill-opacity="0.5" text-anchor="end">Replace in Admin</text>
</svg>
`,
  portrait: ({ primary, accent, dark }) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000" role="img" aria-label="Placeholder image">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${primary}"/>
      <stop offset="1" stop-color="${dark}"/>
    </linearGradient>
  </defs>
  <rect width="800" height="1000" fill="url(#g)"/>
  <g fill="none" stroke="${accent}" stroke-opacity="0.45" stroke-width="6">
    <circle cx="400" cy="470" r="110"/>
    <circle cx="400" cy="470" r="64"/>
  </g>
  <circle cx="400" cy="470" r="13" fill="${accent}" fill-opacity="0.55"/>
  <text x="760" y="968" font-family="system-ui, sans-serif" font-size="26" fill="#ffffff" fill-opacity="0.5" text-anchor="end">Replace in Admin</text>
</svg>
`,
  card: ({ primary, accent, dark }) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 900" role="img" aria-label="Placeholder image">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${primary}"/>
      <stop offset="1" stop-color="${dark}"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="900" fill="url(#g)"/>
  <g fill="none" stroke="${accent}" stroke-opacity="0.45" stroke-width="6">
    <circle cx="600" cy="420" r="100"/>
    <circle cx="600" cy="420" r="58"/>
  </g>
  <circle cx="600" cy="420" r="12" fill="${accent}" fill-opacity="0.55"/>
  <text x="1160" y="868" font-family="system-ui, sans-serif" font-size="24" fill="#ffffff" fill-opacity="0.5" text-anchor="end">Replace in Admin</text>
</svg>
`,
  logo: ({ primary, accent }) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Logo placeholder">
  <g fill="none" stroke="${accent}" stroke-width="22">
    <circle cx="256" cy="256" r="150"/>
    <circle cx="256" cy="256" r="88"/>
  </g>
  <circle cx="256" cy="256" r="30" fill="${primary}"/>
</svg>
`,
};

/** @param {ChurchInput} input @returns {string} */
export function buildChecklist(input) {
  const n = input.names;
  const L = [];
  L.push(`# Provisioning checklist — ${input.name}`);
  L.push('');
  L.push('Generated by `scripts/new-church.mjs`. Run these from the repo root, in order.');
  L.push('Each `wrangler` call may prompt you to log in first (`npx wrangler login`).');
  L.push('');
  L.push('> **Fast path:** run `node scripts/new-church.mjs --provision` (with `CLOUDFLARE_ACCOUNT_ID` set)');
  L.push('> to do steps 1–5 automatically. Preview first with `--provision --dry-run`.');
  L.push('');
  L.push('## 1. Create Cloudflare resources');
  L.push('');
  L.push('```bash');
  L.push(`npx wrangler d1 create ${n.database}`);
  L.push('#   -> paste the printed database_id into wrangler.jsonc (replace PASTE_FROM_D1_CREATE)');
  L.push('npx wrangler kv namespace create SESSION');
  L.push('#   -> paste the printed id into wrangler.jsonc (replace PASTE_FROM_KV_CREATE)');
  L.push(`npx wrangler r2 bucket create ${n.bucket}`);
  if (input.features.ai) L.push(`npx wrangler vectorize create ${n.vectorize} --dimensions=768 --metric=cosine`);
  L.push('```');
  L.push('');
  L.push('## 2. Migrate + seed the database');
  L.push('');
  L.push('```bash');
  L.push(`npx wrangler d1 migrations apply ${n.database} --remote`);
  L.push(`npx wrangler d1 execute ${n.database} --remote --file db/seed.sql`);
  L.push(`npx wrangler d1 execute ${n.database} --remote --file db/seed_funds.sql`);
  L.push(`npx wrangler d1 execute ${n.database} --remote --file db/seed_lists.sql`);
  L.push('```');
  L.push('');
  L.push('## 3. Secrets');
  L.push('');
  L.push('```bash');
  L.push('npx wrangler secret put TURNSTILE_SECRET_KEY   # spam protection on visit/registration/giving forms');
  if (input.features.giving) L.push('npx wrangler secret put PAYSTACK_SECRET_KEY    # online giving');
  L.push('npx wrangler secret put RESEND_API_KEY         # optional: staff email notifications');
  L.push('```');
  L.push('');
  L.push('## 4. Cloudflare Access (protect the admin) — manual, in the dashboard');
  L.push('');
  L.push('Zero Trust → Access → Applications → Add a **self-hosted** app of type **Workers**:');
  L.push('- Cover BOTH paths on your worker hostname: `admin` AND `api/admin`.');
  L.push('- Policy: Allow → your staff emails (One-time PIN or Google).');
  L.push('');
  L.push('## 5. Deploy');
  L.push('');
  L.push('```bash');
  L.push('npm run deploy');
  L.push('```');
  L.push('');
  L.push('## 6. Post-deploy (Admin → Settings)');
  L.push('');
  if (input.features.giving) {
    L.push(`- Giving: set \`paystack_public_key\`, \`currency=${input.currency}\`, \`giving_enabled=true\`; set the Paystack webhook to \`${input.url}/api/webhooks/paystack\`.`);
  }
  L.push('- Turnstile: create a widget for your hostname → put the secret (step 3) + set `turnstile_site_key`.');
  if (input.features.ai) L.push('- AI search: Admin → Sermons → "Reindex AI search" once sermons exist.');
  L.push('- Replace placeholder images and copy throughout the admin.');
  L.push('');
  return L.join('\n');
}

/** Extract the database_id from `wrangler d1 create` / `d1 info` output. */
export function parseD1Id(output) {
  const m = String(output).match(/"database_id":\s*"([^"]+)"/);
  return m ? m[1] : null;
}

/** Extract the namespace id from `wrangler kv namespace create` output. */
export function parseKvId(output) {
  const m = String(output).match(/"id":\s*"([^"]+)"/);
  return m ? m[1] : null;
}

/** Find a KV namespace id by title in `wrangler kv namespace list` output. */
export function parseKvIdFromList(output, title) {
  try {
    const m = String(output).match(/\[[\s\S]*\]/);
    if (!m) return null;
    const arr = JSON.parse(m[0]);
    const found = Array.isArray(arr) ? arr.find((x) => x && x.title === title) : null;
    return found ? found.id : null;
  } catch {
    return null;
  }
}

/** Replace the PASTE_FROM_* id markers in wrangler.jsonc with real ids (only when provided). */
export function applyResourceIds(wranglerText, ids) {
  let t = wranglerText;
  if (ids.databaseId) t = t.replace('PASTE_FROM_D1_CREATE', ids.databaseId);
  if (ids.kvId) t = t.replace('PASTE_FROM_KV_CREATE', ids.kvId);
  return t;
}

export const DEV_TURNSTILE_SECRET = '1x0000000000000000000000000000000AA';

/**
 * Ordered, feature-aware provisioning plan. Each step:
 *   { key, label, cmd, capture?: 'd1Id'|'kvId', kvTitle?, idempotent?: boolean, stdin?: string }
 * The orchestrator runs cmd via execSync; `capture` writes the parsed id back into wrangler.jsonc;
 * `idempotent` swallows an "already exists" error; `stdin` is piped to the command's stdin.
 * @param {ChurchInput} input
 */
export function provisionPlan(input) {
  const n = input.names;
  const kvTitle = `${input.slug}-SESSION`;
  const steps = [
    { key: 'd1', label: 'Create D1 database', cmd: `npx wrangler d1 create ${n.database}`, capture: 'd1Id' },
    { key: 'kv', label: 'Create KV namespace (SESSION)', cmd: `npx wrangler kv namespace create ${kvTitle}`, capture: 'kvId', kvTitle },
    { key: 'r2', label: 'Create R2 bucket', cmd: `npx wrangler r2 bucket create ${n.bucket}`, idempotent: true },
  ];
  if (input.features.ai) {
    steps.push({
      key: 'vectorize',
      label: 'Create Vectorize index',
      cmd: `npx wrangler vectorize create ${n.vectorize} --dimensions=768 --metric=cosine`,
      idempotent: true,
    });
  }
  steps.push(
    { key: 'migrate', label: 'Apply migrations (remote)', cmd: `npx wrangler d1 migrations apply ${n.database} --remote` },
    { key: 'seed1', label: 'Seed settings + ministries', cmd: `npx wrangler d1 execute ${n.database} --remote --file db/seed.sql` },
    { key: 'seed2', label: 'Seed funds', cmd: `npx wrangler d1 execute ${n.database} --remote --file db/seed_funds.sql` },
    { key: 'seed3', label: 'Seed home cards', cmd: `npx wrangler d1 execute ${n.database} --remote --file db/seed_lists.sql` },
    { key: 'turnstile', label: 'Set dev Turnstile secret', cmd: 'npx wrangler secret put TURNSTILE_SECRET_KEY', stdin: DEV_TURNSTILE_SECRET },
    { key: 'build', label: 'Build the site', cmd: 'npm run build' },
    { key: 'deploy', label: 'Deploy', cmd: 'npx wrangler deploy' },
  );
  return steps;
}
