// One-off: emit INSERT OR IGNORE for every content key at its CURRENT default,
// so Kharis's remote D1 owns its copy before main's defaults go generic.
// Run with: npx vite-node scripts/gen-backfill.ts
import { writeFileSync } from 'node:fs';
import { contentDefaults } from '../src/lib/content/fields';

const rows = Object.entries(contentDefaults())
  .map(([k, v]) => `  ('${k.replace(/'/g, "''")}', '${v.replace(/'/g, "''")}', '2026-06-04 00:00:00', 'kharis-backfill')`)
  .join(',\n');

const sql = `-- Generated by scripts/gen-backfill.ts — freezes Kharis content before main goes generic.
-- Additive + idempotent: only fills keys staff never edited; never overwrites an edit.
INSERT OR IGNORE INTO page_content (key, value, updated_at, updated_by) VALUES
${rows};
`;

writeFileSync('db/kharis-content-backfill.sql', sql);
console.log('Wrote db/kharis-content-backfill.sql with', Object.keys(contentDefaults()).length, 'rows');
