/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// `Env` is generated by `wrangler types` from wrangler.jsonc (DB, MEDIA, ASSETS, ...).
// Aliased so app code refers to a stable, intent-revealing name.
type CloudflareBindings = Env;

declare namespace App {
  interface Locals {
    runtime: { env: CloudflareBindings };
  }
}
