/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Worker bindings (`Env`, generated by `wrangler types` from wrangler.jsonc) are read
// via `import { env } from 'cloudflare:workers'` (see src/lib/runtime.ts) — Astro 6
// removed `Astro.locals.runtime.env`, so there is no App.Locals augmentation here.
